FROM ubuntu:bionic

RUN apt update \
      && apt install -y curl jq

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
      &&  apt-get install -y nodejs

RUN npm -g install yarn

RUN apt install -y software-properties-common \
      && add-apt-repository -y ppa:git-core/ppa \
      && apt update \ 
      && apt -y install git

CMD ./test-hash-change.sh
